CREATE TABLE IF NOT EXISTS USER_REGISTRATION (
    ID              SERIAL PRIMARY KEY,
    EMAIL           VARCHAR(255) NOT NULL,
    FULL_NAME       VARCHAR(255) NOT NULL,
    EMAIL_VERIFIED  BOOLEAN   DEFAULT FALSE,
    PHONE_NUMBER    VARCHAR(20),
    DISPLAY_NAME    VARCHAR(255),
    PHOTO_URL       TEXT,
    DISABLED        BOOLEAN   DEFAULT FALSE,
    CREATE_TIME     TIMESTAMP DEFAULT NOW(),
    UPDATE_TIME     TIMESTAMP DEFAULT NOW(),
    FIRESTORE_UID   VARCHAR(50),
    CHANGE_PASSWORD BOOLEAN   DEFAULT FALSE
);

CREATE INDEX IDX_USERS_EMAIL ON USER_REGISTRATION(EMAIL);
CREATE INDEX IDX_USERS_EMAIL_FULL_NAME ON USER_REGISTRATION(EMAIL, FULL_NAME);

COMMENT ON TABLE USER_REGISTRATION IS 'Registro dos usuários cadastrados no sistema';
COMMENT ON COLUMN USER_REGISTRATION.ID IS 'Id do usuário';
COMMENT ON COLUMN USER_REGISTRATION.EMAIL IS 'Email do usuário';
COMMENT ON COLUMN USER_REGISTRATION.FULL_NAME IS 'Nome completo do usuário';
COMMENT ON COLUMN USER_REGISTRATION.EMAIL_VERIFIED IS 'Email verificado?';
COMMENT ON COLUMN USER_REGISTRATION.PHONE_NUMBER IS 'Numero de telefone';
COMMENT ON COLUMN USER_REGISTRATION.DISPLAY_NAME IS 'Nome de exibição';
COMMENT ON COLUMN USER_REGISTRATION.PHOTO_URL IS 'URL da foto';
COMMENT ON COLUMN USER_REGISTRATION.DISABLED IS 'Indica se o usuário esta ativo';
COMMENT ON COLUMN USER_REGISTRATION.CREATE_TIME IS 'Data e hora de criação';
COMMENT ON COLUMN USER_REGISTRATION.UPDATE_TIME IS 'Data de hora de alteração';
COMMENT ON COLUMN USER_REGISTRATION.FIRESTORE_UID IS 'UID do firebase';
COMMENT ON COLUMN USER_REGISTRATION.CHANGE_PASSWORD IS 'Indica se o usuário deve alterar a senha no login';

INSERT INTO USER_REGISTRATION
(EMAIL, FULL_NAME, EMAIL_VERIFIED, PHONE_NUMBER, DISPLAY_NAME, PHOTO_URL, DISABLED, CREATE_TIME, UPDATE_TIME, FIRESTORE_UID,
 CHANGE_PASSWORD)
VALUES ('default@wareysis.com.br', 'Default User', TRUE, '+5541999999999', 'Default User', NULL, FALSE, NOW(), NOW(), 'default', FALSE);


