CREATE TABLE IF NOT EXISTS INCOME_CATEGORY
(
    USER_ID
    INTEGER
    NOT
    NULL,
    NAME
    VARCHAR
(
    100
) NOT NULL,
    DESCRIPTION TEXT,
    CREATE_TIME TIMESTAMP DEFAULT NOW
(
),
    UPDATE_TIME TIMESTAMP DEFAULT NOW
(
),
    PRIMARY KEY
(
    USER_ID,
    NAME
),
    CONSTRAINT FK_USER_REGISTRATION FOREIGN KEY
(
    USER_ID
) REFERENCES USER_REGISTRATION
(
    ID
) ON DELETE CASCADE
    );

CREATE INDEX IDX_INCOME_CATEGORY_USER_NAME ON INCOME_CATEGORY (USER_ID, NAME);

COMMENT
ON TABLE INCOME_CATEGORY IS 'Categorias de renda';
COMMENT
ON COLUMN INCOME_CATEGORY.USER_ID IS 'Id do usuário';
COMMENT
ON COLUMN INCOME_CATEGORY.NAME IS 'Nome da categoria';
COMMENT
ON COLUMN INCOME_CATEGORY.DESCRIPTION IS 'Descrição da categoria';
COMMENT
ON COLUMN INCOME_CATEGORY.CREATE_TIME IS 'Data e hora da criação da categoria';
COMMENT
ON COLUMN INCOME_CATEGORY.UPDATE_TIME IS 'Data e hora da última alteração da categoria';

INSERT INTO INCOME_CATEGORY (USER_ID, NAME, DESCRIPTION)
VALUES (1, 'Salário', 'Recebimento de salário');

INSERT INTO INCOME_CATEGORY (USER_ID, NAME, DESCRIPTION)
VALUES (1, 'Serviço', 'Receita de serviços prestados');

INSERT INTO INCOME_CATEGORY (USER_ID, NAME, DESCRIPTION)
VALUES (1, 'Cashback', 'Receitas de cashback');

INSERT INTO INCOME_CATEGORY (USER_ID, NAME, DESCRIPTION)
VALUES (1, 'Vendas', 'Receitas com vendas');

INSERT INTO INCOME_CATEGORY (USER_ID, NAME, DESCRIPTION)
VALUES (1, 'Rendimento', 'Receitas com rendimentos');

INSERT INTO INCOME_CATEGORY (USER_ID, NAME, DESCRIPTION)
VALUES (1, 'Outras Entradas', 'Receitas diversas');

INSERT INTO INCOME_CATEGORY (USER_ID, NAME, DESCRIPTION)
VALUES (1, 'Estorno', 'Receitas de estorno');
