CREATE TABLE IF NOT EXISTS ENTRY_TYPE (
    ID          SERIAL PRIMARY KEY,
    NAME        VARCHAR(100) NOT NULL,
    DESCRIPTION TEXT
);

COMMENT ON TABLE ENTRY_TYPE IS 'Tipo de registro';
COMMENT ON COLUMN ENTRY_TYPE.ID IS 'Id do tipo';
COMMENT ON COLUMN ENTRY_TYPE.NAME IS 'Nome do tipo';
COMMENT ON COLUMN ENTRY_TYPE.DESCRIPTION IS 'Descrição do tipo';

ALTER TABLE ENTRY_TYPE
ADD CONSTRAINT UQ_ENTRY_TYPE_NAME UNIQUE (NAME);

INSERT INTO ENTRY_TYPE (NAME, DESCRIPTION)
VALUES ('Fixa', 'Despesa e/ou Receita com valor fixo');

INSERT INTO ENTRY_TYPE (NAME, DESCRIPTION)
VALUES ('Variável', 'Despesa e/ou Receita com valor variável');
