CREATE TABLE IF NOT EXISTS STATUS_TYPE (
    ID          SERIAL PRIMARY KEY,
    NAME        VARCHAR(100) NOT NULL,
    DESCRIPTION TEXT,
    CREATE_TIME TIMESTAMP    NOT NULL DEFAULT NOW(),
    UPDATE_TIME TIMESTAMP    NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE STATUS_TYPE IS 'Status dos registros';
COMMENT ON COLUMN STATUS_TYPE.ID IS 'Id do status';
COMMENT ON COLUMN STATUS_TYPE.NAME IS 'Nome do status';
COMMENT ON COLUMN STATUS_TYPE.DESCRIPTION IS 'Descrição do status';

ALTER TABLE STATUS_TYPE
ADD CONSTRAINT UQ_STATUS_TYPE_NAME UNIQUE (NAME);

INSERT INTO STATUS_TYPE (NAME, DESCRIPTION)
VALUES ('Em Aberto', 'Despesa e/ou Receita com valor em aberto');

INSERT INTO STATUS_TYPE (NAME, DESCRIPTION)
VALUES ('Em Andamento', 'Despesa e/ou Receita em andamento');

INSERT INTO STATUS_TYPE (NAME, DESCRIPTION)
VALUES ('Pago', 'Despesa e/ou Receita paga');

INSERT INTO STATUS_TYPE (NAME, DESCRIPTION)
VALUES ('Finalizado', 'Despesa e/ou Receita finalizada');

INSERT INTO STATUS_TYPE (NAME, DESCRIPTION)
VALUES ('Cancelado', 'Despesa e/ou Receita cancelada');
