CREATE EXTENSION IF NOT EXISTS "pgcrypto";

CREATE TABLE IF NOT EXISTS EXPENSE_INSTALLMENT (
    ID          UUID           NOT NULL DEFAULT GEN_RANDOM_UUID(),
    ENTRY_ID    BIGINT         NOT NULL,
    USER_ID     INTEGER        NOT NULL,
    ENTRY_DATE  DATE           NOT NULL,
    DUE_DATE    DATE           NOT NULL,
    AMOUNT      DECIMAL(12, 3) NOT NULL,
    STATUS_TYPE INTEGER        NOT NULL,
    AMOUNT_PAID DECIMAL(12, 3) NOT NULL DEFAULT 0,
    CREATE_TIME TIMESTAMP      NOT NULL DEFAULT NOW(),
    UPDATE_TIME TIMESTAMP      NOT NULL DEFAULT NOW(),
    PRIMARY KEY (ID, DUE_DATE),

    CONSTRAINT FK_ENTRY_ID FOREIGN KEY (ENTRY_ID, USER_ID, ENTRY_DATE) REFERENCES EXPENSE_ENTRY(ID, USER_ID, ENTRY_DATE),
    CONSTRAINT FK_USER_REGISTRATION FOREIGN KEY (USER_ID) REFERENCES USER_REGISTRATION(ID) ON DELETE CASCADE,
    CONSTRAINT FK_STATUS_TYPE FOREIGN KEY (STATUS_TYPE) REFERENCES STATUS_TYPE(ID)

) PARTITION BY RANGE (DUE_DATE);

-- Índices na tabela principal (tabela pai)
CREATE INDEX IDX_EXPENSE_INSTALLMENT_USER_STATUS_TYPE ON EXPENSE_INSTALLMENT(USER_ID, STATUS_TYPE);
CREATE INDEX IDX_EXPENSE_INSTALLMENT_USER_ENTRY_DATE ON EXPENSE_INSTALLMENT(USER_ID, ENTRY_DATE);
CREATE INDEX IDX_EXPENSE_INSTALLMENT_USER_DUE_DATE ON EXPENSE_INSTALLMENT(USER_ID, DUE_DATE);

-- Comentários na tabela
COMMENT ON TABLE EXPENSE_INSTALLMENT IS 'Parcelas das despesas';
COMMENT ON COLUMN EXPENSE_INSTALLMENT.ID IS 'Id da parcela';
COMMENT ON COLUMN EXPENSE_INSTALLMENT.ENTRY_ID IS 'Id da despesa';
COMMENT ON COLUMN EXPENSE_INSTALLMENT.USER_ID IS 'ID do usuário';
COMMENT ON COLUMN EXPENSE_INSTALLMENT.ENTRY_DATE IS 'Data da despesa';
COMMENT ON COLUMN EXPENSE_INSTALLMENT.DUE_DATE IS 'Data do vencimento da parcela';
COMMENT ON COLUMN EXPENSE_INSTALLMENT.AMOUNT IS 'Valor da parcela';
COMMENT ON COLUMN EXPENSE_INSTALLMENT.STATUS_TYPE IS 'Id do status da parcela';
COMMENT ON COLUMN EXPENSE_INSTALLMENT.AMOUNT_PAID IS 'Valor pago';
COMMENT ON COLUMN EXPENSE_INSTALLMENT.CREATE_TIME IS 'Data e hora do lançamento da parcela';
COMMENT ON COLUMN EXPENSE_INSTALLMENT.UPDATE_TIME IS 'Data e hora da última alteração na parcela';

-- Partição para o ano de 2023
CREATE TABLE EXPENSE_INSTALLMENT_2023 PARTITION OF EXPENSE_INSTALLMENT
    FOR VALUES FROM ('2023-01-01') TO ('2023-12-31');

-- Partição para o ano de 2024
CREATE TABLE EXPENSE_INSTALLMENT_2024 PARTITION OF EXPENSE_INSTALLMENT
    FOR VALUES FROM ('2024-01-01') TO ('2024-12-31');

-- Partição para o ano de 2025
CREATE TABLE EXPENSE_INSTALLMENT_2025 PARTITION OF EXPENSE_INSTALLMENT
    FOR VALUES FROM ('2025-01-01') TO ('2025-12-31');

-- Partição para o ano de 2026
CREATE TABLE EXPENSE_INSTALLMENT_2026 PARTITION OF EXPENSE_INSTALLMENT
    FOR VALUES FROM ('2026-01-01') TO ('2026-12-31');

-- Partição para o ano de 2027
CREATE TABLE EXPENSE_INSTALLMENT_2027 PARTITION OF EXPENSE_INSTALLMENT
    FOR VALUES FROM ('2027-01-01') TO ('2027-12-31');

-- Partição para o ano de 2028
CREATE TABLE EXPENSE_INSTALLMENT_2028 PARTITION OF EXPENSE_INSTALLMENT
    FOR VALUES FROM ('2028-01-01') TO ('2028-12-31');

-- Partição para o ano de 2029
CREATE TABLE EXPENSE_INSTALLMENT_2029 PARTITION OF EXPENSE_INSTALLMENT
    FOR VALUES FROM ('2029-01-01') TO ('2029-12-31');

-- Partição para o ano de 2030
CREATE TABLE EXPENSE_INSTALLMENT_2030 PARTITION OF EXPENSE_INSTALLMENT
    FOR VALUES FROM ('2030-01-01') TO ('2030-12-31');

-- Partição para o ano de 2031
CREATE TABLE EXPENSE_INSTALLMENT_2031 PARTITION OF EXPENSE_INSTALLMENT
    FOR VALUES FROM ('2031-01-01') TO ('2031-12-31');

-- Partição para o ano de 2032
CREATE TABLE EXPENSE_INSTALLMENT_2032 PARTITION OF EXPENSE_INSTALLMENT
    FOR VALUES FROM ('2032-01-01') TO ('2032-12-31');

-- Partição para o ano de 2033
CREATE TABLE EXPENSE_INSTALLMENT_2033 PARTITION OF EXPENSE_INSTALLMENT
    FOR VALUES FROM ('2033-01-01') TO ('2033-12-31');

-- Partição para o ano de 2034
CREATE TABLE EXPENSE_INSTALLMENT_2034 PARTITION OF EXPENSE_INSTALLMENT
    FOR VALUES FROM ('2034-01-01') TO ('2034-12-31');

-- Partição para o ano de 2035
CREATE TABLE EXPENSE_INSTALLMENT_2035 PARTITION OF EXPENSE_INSTALLMENT
    FOR VALUES FROM ('2035-01-01') TO ('2035-12-31');

-- Indices para 2023
CREATE INDEX IF NOT EXISTS IDX_EXPENSE_INSTALLMENT_2023_USER_STATUS_TYPE ON EXPENSE_INSTALLMENT_2023(USER_ID, STATUS_TYPE);
CREATE INDEX IF NOT EXISTS IDX_EXPENSE_INSTALLMENT_2023_USER_ENTRY_DATE ON EXPENSE_INSTALLMENT_2023(USER_ID, ENTRY_DATE);
CREATE INDEX IF NOT EXISTS IDX_EXPENSE_INSTALLMENT_2023_USER_DUE_DATE ON EXPENSE_INSTALLMENT_2023(USER_ID, DUE_DATE);

-- Indices para 2024
CREATE INDEX IF NOT EXISTS IDX_EXPENSE_INSTALLMENT_2024_USER_STATUS_TYPE ON EXPENSE_INSTALLMENT_2024(USER_ID, STATUS_TYPE);
CREATE INDEX IF NOT EXISTS IDX_EXPENSE_INSTALLMENT_2024_USER_ENTRY_DATE ON EXPENSE_INSTALLMENT_2024(USER_ID, ENTRY_DATE);
CREATE INDEX IF NOT EXISTS IDX_EXPENSE_INSTALLMENT_2024_USER_DUE_DATE ON EXPENSE_INSTALLMENT_2024(USER_ID, DUE_DATE);

-- Indices para 2025
CREATE INDEX IF NOT EXISTS IDX_EXPENSE_INSTALLMENT_2025_USER_STATUS_TYPE ON EXPENSE_INSTALLMENT_2025(USER_ID, STATUS_TYPE);
CREATE INDEX IF NOT EXISTS IDX_EXPENSE_INSTALLMENT_2025_USER_ENTRY_DATE ON EXPENSE_INSTALLMENT_2025(USER_ID, ENTRY_DATE);
CREATE INDEX IF NOT EXISTS IDX_EXPENSE_INSTALLMENT_2025_USER_DUE_DATE ON EXPENSE_INSTALLMENT_2025(USER_ID, DUE_DATE);

-- Indices para 2026
CREATE INDEX IF NOT EXISTS IDX_EXPENSE_INSTALLMENT_2026_USER_STATUS_TYPE ON EXPENSE_INSTALLMENT_2026(USER_ID, STATUS_TYPE);
CREATE INDEX IF NOT EXISTS IDX_EXPENSE_INSTALLMENT_2026_USER_ENTRY_DATE ON EXPENSE_INSTALLMENT_2026(USER_ID, ENTRY_DATE);
CREATE INDEX IF NOT EXISTS IDX_EXPENSE_INSTALLMENT_2026_USER_DUE_DATE ON EXPENSE_INSTALLMENT_2026(USER_ID, DUE_DATE);

-- Indices para 2027
CREATE INDEX IF NOT EXISTS IDX_EXPENSE_INSTALLMENT_2027_USER_STATUS_TYPE ON EXPENSE_INSTALLMENT_2027(USER_ID, STATUS_TYPE);
CREATE INDEX IF NOT EXISTS IDX_EXPENSE_INSTALLMENT_2027_USER_ENTRY_DATE ON EXPENSE_INSTALLMENT_2027(USER_ID, ENTRY_DATE);
CREATE INDEX IF NOT EXISTS IDX_EXPENSE_INSTALLMENT_2027_USER_DUE_DATE ON EXPENSE_INSTALLMENT_2027(USER_ID, DUE_DATE);

-- Indices para 2028
CREATE INDEX IF NOT EXISTS IDX_EXPENSE_INSTALLMENT_2028_USER_STATUS_TYPE ON EXPENSE_INSTALLMENT_2028(USER_ID, STATUS_TYPE);
CREATE INDEX IF NOT EXISTS IDX_EXPENSE_INSTALLMENT_2028_USER_ENTRY_DATE ON EXPENSE_INSTALLMENT_2028(USER_ID, ENTRY_DATE);
CREATE INDEX IF NOT EXISTS IDX_EXPENSE_INSTALLMENT_2028_USER_DUE_DATE ON EXPENSE_INSTALLMENT_2028(USER_ID, DUE_DATE);

-- Indices para 2029
CREATE INDEX IF NOT EXISTS IDX_EXPENSE_INSTALLMENT_2029_USER_STATUS_TYPE ON EXPENSE_INSTALLMENT_2029(USER_ID, STATUS_TYPE);
CREATE INDEX IF NOT EXISTS IDX_EXPENSE_INSTALLMENT_2029_USER_ENTRY_DATE ON EXPENSE_INSTALLMENT_2029(USER_ID, ENTRY_DATE);
CREATE INDEX IF NOT EXISTS IDX_EXPENSE_INSTALLMENT_2029_USER_DUE_DATE ON EXPENSE_INSTALLMENT_2029(USER_ID, DUE_DATE);

-- Indices para 2030
CREATE INDEX IF NOT EXISTS IDX_EXPENSE_INSTALLMENT_2030_USER_STATUS_TYPE ON EXPENSE_INSTALLMENT_2030(USER_ID, STATUS_TYPE);
CREATE INDEX IF NOT EXISTS IDX_EXPENSE_INSTALLMENT_2030_USER_ENTRY_DATE ON EXPENSE_INSTALLMENT_2030(USER_ID, ENTRY_DATE);
CREATE INDEX IF NOT EXISTS IDX_EXPENSE_INSTALLMENT_2030_USER_DUE_DATE ON EXPENSE_INSTALLMENT_2030(USER_ID, DUE_DATE);

-- Indices para 2031
CREATE INDEX IF NOT EXISTS IDX_EXPENSE_INSTALLMENT_2031_USER_STATUS_TYPE ON EXPENSE_INSTALLMENT_2031(USER_ID, STATUS_TYPE);
CREATE INDEX IF NOT EXISTS IDX_EXPENSE_INSTALLMENT_2031_USER_ENTRY_DATE ON EXPENSE_INSTALLMENT_2031(USER_ID, ENTRY_DATE);
CREATE INDEX IF NOT EXISTS IDX_EXPENSE_INSTALLMENT_2031_USER_DUE_DATE ON EXPENSE_INSTALLMENT_2031(USER_ID, DUE_DATE);

-- Indices para 2032
CREATE INDEX IF NOT EXISTS IDX_EXPENSE_INSTALLMENT_2032_USER_STATUS_TYPE ON EXPENSE_INSTALLMENT_2032(USER_ID, STATUS_TYPE);
CREATE INDEX IF NOT EXISTS IDX_EXPENSE_INSTALLMENT_2032_USER_ENTRY_DATE ON EXPENSE_INSTALLMENT_2032(USER_ID, ENTRY_DATE);
CREATE INDEX IF NOT EXISTS IDX_EXPENSE_INSTALLMENT_2032_USER_DUE_DATE ON EXPENSE_INSTALLMENT_2032(USER_ID, DUE_DATE);

-- Indices para 2033
CREATE INDEX IF NOT EXISTS IDX_EXPENSE_INSTALLMENT_2033_USER_STATUS_TYPE ON EXPENSE_INSTALLMENT_2033(USER_ID, STATUS_TYPE);
CREATE INDEX IF NOT EXISTS IDX_EXPENSE_INSTALLMENT_2033_USER_ENTRY_DATE ON EXPENSE_INSTALLMENT_2033(USER_ID, ENTRY_DATE);
CREATE INDEX IF NOT EXISTS IDX_EXPENSE_INSTALLMENT_2033_USER_DUE_DATE ON EXPENSE_INSTALLMENT_2033(USER_ID, DUE_DATE);

-- Indices para 2034
CREATE INDEX IF NOT EXISTS IDX_EXPENSE_INSTALLMENT_2034_USER_STATUS_TYPE ON EXPENSE_INSTALLMENT_2034(USER_ID, STATUS_TYPE);
CREATE INDEX IF NOT EXISTS IDX_EXPENSE_INSTALLMENT_2034_USER_ENTRY_DATE ON EXPENSE_INSTALLMENT_2034(USER_ID, ENTRY_DATE);
CREATE INDEX IF NOT EXISTS IDX_EXPENSE_INSTALLMENT_2034_USER_DUE_DATE ON EXPENSE_INSTALLMENT_2034(USER_ID, DUE_DATE);

-- Indices para 2035
CREATE INDEX IF NOT EXISTS IDX_EXPENSE_INSTALLMENT_2035_USER_STATUS_TYPE ON EXPENSE_INSTALLMENT_2035(USER_ID, STATUS_TYPE);
CREATE INDEX IF NOT EXISTS IDX_EXPENSE_INSTALLMENT_2035_USER_ENTRY_DATE ON EXPENSE_INSTALLMENT_2035(USER_ID, ENTRY_DATE);
CREATE INDEX IF NOT EXISTS IDX_EXPENSE_INSTALLMENT_2035_USER_DUE_DATE ON EXPENSE_INSTALLMENT_2035(USER_ID, DUE_DATE);



